redis:
  image: redis
  container_name: cache
  expose:
    - 8000
app:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
  ports:
    - 8000:8000
    # local machine port : docker container port
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=8000
  command:
    sh -c 'npm i && node app.js'