apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-deployment
  labels:
    app: question
spec:
  selector:
    matchLabels:
      app: question
  replicas: 2
  template:
    metadata:
      labels:
        app: question
    spec:
      containers:
      - name: question
        image: 852678264376.dkr.ecr.ap-southeast-1.amazonaws.com/cs3219:question-service
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: ad64871ba1aac4ec09cc6607627f92e9-1108944277.ap-southeast-1.elb.amazonaws.com
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: 'admin123!@#'
        - name: DB_NAME
          value: cs3219
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  selector:
    app: question