apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-deployment
  labels:
    app: matching
spec:
  selector:
    matchLabels:
      app: matching
  replicas: 1
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
      - name: matching
        image: 852678264376.dkr.ecr.ap-southeast-1.amazonaws.com/cs3219:matching-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: matching-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: matching