apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-deployment
  labels:
    app: collab
spec:
  selector:
    matchLabels:
      app: collab
  replicas: 2
  template:
    metadata:
      labels:
        app: collab
    spec:
      containers:
      - name: collab
        image: 852678264376.dkr.ecr.ap-southeast-1.amazonaws.com/cs3219:collab-service
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: collab-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: collab