name: Collab Service CI/CD Workflow

on:
  push:
    paths:
    - 'backend/collaborationService/**'

jobs:
  deploy: 
    name: Deploy Collaboration Service to AWS ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA4NB4VYY4JGKP67XK
        aws-secret-access-key: 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
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 852678264376.dkr.ecr.ap-southeast-1.amazonaws.com
        ECR_REPOSITORY: cs3219
        IMAGE_TAG: collab-service
      run: |
        # Build a docker container and push it to ECR
        cd backend/collaborationService
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG.${GITHUB_RUN_NUMBER} .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG.${GITHUB_RUN_NUMBER}
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG.${GITHUB_RUN_NUMBER}"

    - name: Deploy to AWS EKS                                                                         
      uses: kodermax/kubectl-aws-eks@master                                                                         
      env:
        ECR_REGISTRY: 852678264376.dkr.ecr.ap-southeast-1.amazonaws.com
        ECR_REPOSITORY: cs3219
        IMAGE_TAG: collab-service                                                                                                          
        RELEASE_IMAGE: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG.${GITHUB_RUN_NUMBER}
      with:                                                                                                         
        args: set image deployment/my-pod app=${{ env.RELEASE_IMAGE }} 