name: Frontend CI/CD Workflow

on:
  push:
    paths:
    - 'frontend/**'
    - '.github/workflows/frontend.yml'

jobs:
  deploy: 
    name: Deploy frontend to AWS ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 852678264376.dkr.ecr.ap-southeast-1.amazonaws.com
        ECR_REPOSITORY: cs3219
        IMAGE_TAG: frontend
      run: |
        # Build a docker container and push it to ECR
        cd frontend
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG.${GITHUB_RUN_NUMBER} .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG.${GITHUB_RUN_NUMBER}
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG.${GITHUB_RUN_NUMBER}"

    - name: Deploy to AWS EKS                                                                         
      uses: kodermax/kubectl-aws-eks@master                                                                         
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        ECR_REGISTRY: 852678264376.dkr.ecr.ap-southeast-1.amazonaws.com
        ECR_REPOSITORY: cs3219
        IMAGE_TAG: frontend                                                                                                       
        RELEASE_IMAGE: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG.${GITHUB_RUN_NUMBER}
      with:                                                                                                         
        args: set image deployment/user-deployment matching=${{ env.RELEASE_IMAGE }} 