name: Frontend CI/CD Workflow

on:
  push:
    paths:
    - 'frontend/**'

jobs:
  deploy: 
    name: Deploy frontend to AWS ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIA4NB4VYY4JGKP67XK
        aws-secret-access-key: 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
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 852678264376.dkr.ecr.ap-southeast-1.amazonaws.com
        ECR_REPOSITORY: cs3219
        IMAGE_TAG: frontend
      run: |
        # Build a docker container and push it to ECR
        cd frontend
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"